# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SPARK CI with Maven

# triggered on push pr, only spark module is modified

on:
  push:
    branches:
      - "master"
      - "0.**"
    paths:
      - "spark/**"
      - "!core/**"
      - "!hive/**"
      - "!ams/**"

  pull_request:
    branches:
      - "master"
      - "0.**"
    paths:
      - "spark/**"
      - "!core/**"
      - "!hive/**"
      - "!ams/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Get changed file
        id: changed-files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            spark23:
              - 'spark/v2.3/**'
            spark31:
              - 'spark/v3.1/**'

      - name: test for spark 2.3
        if: steps.changed-files.outputs.spark23 == 'true'
        run: mvn install -pl 'spark/v2.3/spark' -am -e

      - name: test for spark 3.1
        if: steps.changed-files.outputs.spark31 == 'true'
        run: mvn install -pl 'spark/v3.1/spark-runtime,ams/ams-server' -am -e